<script lang="ts">
</script>

<h1 class="text-3xl font-medium mb-2">Settings</h1>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Condimentum id venenatis a condimentum vitae sapien pellentesque. Viverra mauris in aliquam sem. Ut sem viverra aliquet eget sit. Viverra maecenas accumsan lacus vel facilisis volutpat. Diam maecenas sed enim ut. Pharetra sit amet aliquam id diam. Velit scelerisque in dictum non. Maecenas accumsan lacus vel facilisis volutpat est velit egestas dui. Vivamus at augue eget arcu dictum varius duis at consectetur. Cursus euismod quis viverra nibh cras. Massa id neque aliquam vestibulum morbi blandit cursus. At varius vel pharetra vel. Turpis nunc eget lorem dolor.

Sem integer vitae justo eget magna. Sit amet justo donec enim diam vulputate ut pharetra. Varius morbi enim nunc faucibus a pellentesque. Habitant morbi tristique senectus et netus et. Nulla malesuada pellentesque elit eget. Suspendisse faucibus interdum posuere lorem ipsum dolor sit. Mi in nulla posuere sollicitudin aliquam ultrices sagittis. Augue interdum velit euismod in pellentesque. Egestas sed sed risus pretium quam. At urna condimentum mattis pellentesque id. Sapien et ligula ullamcorper malesuada proin. Turpis massa tincidunt dui ut ornare lectus sit. Urna cursus eget nunc scelerisque. Nullam eget felis eget nunc lobortis mattis aliquam. Diam donec adipiscing tristique risus nec feugiat in. Viverra nibh cras pulvinar mattis. Blandit turpis cursus in hac habitasse platea.

Augue neque gravida in fermentum et sollicitudin ac. Mauris ultrices eros in cursus. Sed faucibus turpis in eu mi bibendum neque. Molestie at elementum eu facilisis. Dictumst quisque sagittis purus sit amet volutpat consequat. Convallis posuere morbi leo urna molestie at. Sed turpis tincidunt id aliquet risus feugiat in ante metus. Mauris ultrices eros in cursus turpis. Scelerisque felis imperdiet proin fermentum leo. Cursus vitae congue mauris rhoncus aenean vel elit. Elit scelerisque mauris pellentesque pulvinar.

Elit sed vulputate mi sit amet mauris. Amet consectetur adipiscing elit pellentesque habitant morbi tristique. Est velit egestas dui id. Vitae auctor eu augue ut lectus arcu bibendum. Aliquam nulla facilisi cras fermentum odio. Tincidunt ornare massa eget egestas purus. Nibh sit amet commodo nulla facilisi nullam. Sollicitudin aliquam ultrices sagittis orci a scelerisque. Egestas fringilla phasellus faucibus scelerisque. Ornare aenean euismod elementum nisi quis. Risus quis varius quam quisque id diam vel quam. Scelerisque varius morbi enim nunc faucibus a pellentesque sit amet. Morbi tincidunt augue interdum velit. Eget magna fermentum iaculis eu non diam phasellus. Ante metus dictum at tempor commodo ullamcorper a.

Nisl purus in mollis nunc sed. Tortor at risus viverra adipiscing at. Enim nulla aliquet porttitor lacus luctus accumsan. Vulputate ut pharetra sit amet aliquam id diam maecenas. At varius vel pharetra vel turpis nunc eget lorem dolor. Fames ac turpis egestas integer eget aliquet. In mollis nunc sed id semper. Non tellus orci ac auctor. Mauris a diam maecenas sed. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Dignissim convallis aenean et tortor at risus. Nunc aliquet bibendum enim facilisis gravida.

Facilisis magna etiam tempor orci eu lobortis. Pulvinar mattis nunc sed blandit libero. Magna sit amet purus gravida quis blandit turpis. Molestie nunc non blandit massa. Bibendum arcu vitae elementum curabitur. Mattis vulputate enim nulla aliquet porttitor lacus luctus. Dictum fusce ut placerat orci nulla pellentesque dignissim. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Vitae semper quis lectus nulla at. Sit amet purus gravida quis blandit turpis cursus in. Magna eget est lorem ipsum dolor sit amet. Ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum. Egestas maecenas pharetra convallis posuere morbi leo. Placerat duis ultricies lacus sed turpis tincidunt id aliquet. Enim lobortis scelerisque fermentum dui. Porttitor eget dolor morbi non. Sociis natoque penatibus et magnis dis parturient montes nascetur. Eu mi bibendum neque egestas congue quisque egestas. Nunc mattis enim ut tellus elementum sagittis.

Eget dolor morbi non arcu risus quis. Neque vitae tempus quam pellentesque. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus quam. Fermentum iaculis eu non diam phasellus vestibulum lorem sed. Elementum curabitur vitae nunc sed velit dignissim sodales ut eu. Tincidunt ornare massa eget egestas purus viverra accumsan in. Est lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Iaculis nunc sed augue lacus viverra vitae congue. At elementum eu facilisis sed odio morbi quis commodo odio. Quam nulla porttitor massa id neque. Egestas purus viverra accumsan in nisl. Amet consectetur adipiscing elit duis tristique sollicitudin nibh. Elit ullamcorper dignissim cras tincidunt lobortis. In eu mi bibendum neque.

Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Egestas dui id ornare arcu odio ut sem. Dignissim enim sit amet venenatis urna cursus eget nunc scelerisque. Bibendum at varius vel pharetra vel turpis nunc. Donec massa sapien faucibus et. Eget nullam non nisi est sit amet. Purus in mollis nunc sed id semper risus in hendrerit. Nisl rhoncus mattis rhoncus urna neque viverra justo nec. Pharetra massa massa ultricies mi quis. Purus in massa tempor nec feugiat nisl pretium fusce id. Netus et malesuada fames ac turpis egestas maecenas pharetra. Netus et malesuada fames ac.

Facilisis magna etiam tempor orci. Nam at lectus urna duis convallis convallis. Aliquam faucibus purus in massa tempor nec feugiat nisl. Vitae congue eu consequat ac felis donec. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Diam volutpat commodo sed egestas egestas fringilla phasellus. Sapien nec sagittis aliquam malesuada bibendum arcu vitae. Malesuada fames ac turpis egestas integer eget aliquet. Consequat interdum varius sit amet mattis vulputate. Ut porttitor leo a diam sollicitudin tempor id eu.

Dui vivamus arcu felis bibendum ut tristique et. Etiam non quam lacus suspendisse faucibus. Lectus sit amet est placerat in. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non. Purus non enim praesent elementum facilisis leo vel fringilla est. Ac turpis egestas maecenas pharetra convallis posuere morbi. Eu non diam phasellus vestibulum. Integer vitae justo eget magna fermentum iaculis eu non diam. Commodo ullamcorper a lacus vestibulum sed arcu non odio. Volutpat est velit egestas dui id ornare arcu. Amet nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Viverra accumsan in nisl nisi scelerisque eu. Orci porta non pulvinar neque laoreet suspendisse interdum. Turpis nunc eget lorem dolor sed viverra ipsum nunc. Mi sit amet mauris commodo quis imperdiet. Eget gravida cum sociis natoque penatibus et magnis. Nisi quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Dolor sit amet consectetur adipiscing elit duis tristique. Elit at imperdiet dui accumsan sit.